# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89f45f295ae498f77ae963397f1e9b29c223b07c2853c60a65f7e8ffb89aceda2a6f3f034133a310a81a3774a180255c87c2d3b3e9dc4257035f958410569fd4

test:
  secret_key_base: 9d1348a42e86ee27d10304b1e47613609e4b935323355d3d6179e8ca19645e8aba84734553200b62233d5fbe130b7354dd1d6f18130293904f2806a1d35cc3cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
